== Making an Index

`make_index` is a Ruby program for generating
an index for Asciidoc documents.  At the
moment it requires the `Asciidoctor-LaTeX` extension.footnote:[The
dependence is entirely on the use of the inline macro
`index_term`  Some css
is also required. ]



Mark terms as in the following examples if you want them to appear
in the document index:
----
   ((potrezebie))
----
The index term will be displayed in red in the text and will
appear in the index as a hyperlink to the given term

Use the following syntax to produce entries in the index
without visibly altering the renderd text.   However, the
index entries thus make are links back to the original
text.  See the file `keynes_ch_2-indexed.adoc` for
examples

* `+(((Postulates of Economic Theory)))+`
* `+(((Theory, Postulates of)))+`
* `+(((Theory, Economic, Postulates of)))+`

The corresponding index entries are
----
Postulates of Economic Theory
Theory
  Postulates of
Theory
  Economic
    Postulates of
----


Assuming that your document is `foo.adoc`, do
this to make a version with an index:
----
  $ ruby make_index.rb ../examples/foo.adoc
----
Execution of this command produces
two files, `foo-indexed.adoc`
and `foo-indexed.html`.  Here we assume
that you in the directory `make_index/lib`.

https://vschool.s3.amazonaws.com/manuscripts/462.html[Here]
is an example of an Asciidoc document compiled
with an index.  And
http://www.noteshare.io/lessons/index-example-1?remote=true&view_mode=source[here]
is a place to view the source text if you are
logged in to Noteshare.  If you wish,
you can sign up for
a free account at
http://www.noteshare.io[Noteshare.io].


.Larger Example
For testing purposes, the 5900-word file
`keynes_ch_2.adoc` is included.
It has a few terms marked marked for the
index.  To play with it, do this:
----
  $  ruby make_index.rb ../examples/keynes_ch_2.adoc
----
Then view the file `keynes_ch_2-indexed.html`
in your browser.

=== Installation

.Download from GitHub
----
  $ git clone https://github.com/jxxcarlson/asciidoctor-make-index
  $ https://github.com/asciidoctor/asciidoctor-latex
  $ cd asciidoctor-latex
  $ rake install
----

Run tests with `rspec spec/make_index_spec.rb`.

.Stopgap
Until I get things properly set up build and install
a gem, you should also
say

----
alias makeindex="ruby $HOME/dev/git/asciidoctor-make-index/lib/make_index.rb"
----

Then you can run `make-index foo.adoc` from anywhere.

.Help needed
When I run `rake install`, the gem is installed
as `make_index (0.1.0)` (verified)
by running `gem list`). but when I run `$ make_index foo.adoc`
I get the error 'make_index: command not found'

=== Notes

. The index feature of Asciidoctor-LaTeX experimental.
It is designed to be syntax-compatible with the
corresponding feature for Asciidoctor when
it is released.  At that point,
`make_index.rb` will be redundant.
. The index feature has beeb rolled into
http://www.noteshare.io[Noteshare.io].  The *Show Doc*
item in the *View* menu will compile the current notebook
with an index if the attribute `:make_index:` is set.
See http://www.noteshare.io/section/writing-tools#_index[this document]
