== Making an Index

`make_index` is a Ruby program for generating
an index for Asciidoc documents.  At the
moment it requires the `Asciidoctor-LaTeX` extension.


Mark terms like this if you want them to appear
in the document index:
----
   ((potrezebie))
----
Assuming that your document is `foo.adoc`, follow
these steps to make a version with an index:
----
  $ ruby make_index.rb foo.adoc
  $ asciidoctor-latex -b html foo-indexed.adoc
----
The rendered file will be `foo-indexed.html`.
This example assumes that you are in
the directory `examples`.

.Larger Example
For testing purposes, the 5900-word file
`keynes_ch_2.adoc` is included.
It has a few terms marked marked for the
index.  To play with it, do this:
----
  $  ruby make_index.rb keynes_ch_2.adoc
  $  asciidoctor-latex keynes_ch_2-indexed.adoc
----
Then view the file `keynes_ch_2-indexed.html`
in your browser.

=== Installation

.Download from GitHub
----
  $ git clone https://github.com/jxxcarlson/asciidoctor-make-index
  $ https://github.com/asciidoctor/asciidoctor-latex
  $ cd asciidoctor-latex
  $ rake install
----

Run tests with `rspec spec/make_index_spec.rb`.

.Stopgap
Until I get things properly set up build and install
a gem, you should also
say

----
alias make-index="ruby $HOME/dev/git/asciidoctor-make-index/lib/make_index.rb"
----

Then you can run `make-index foo.adoc` from anywhere.

.Help needed
When I run `rake install`, the gem is installed
as `make_index (0.1.0)` (verified)
by running `gem list`). but when I run `$ make_index foo.adoc`
I get the error 'make_index: command not found'

=== Notes

. The index feature of Asciidoctor-LaTeX experimental.
It is designed to be syntax-compatible with the
corresponding feature for Asciidoctor when
it is released.  At that point,
`make_index.rb` will be redundant.
. In the next few days, the index feature will be rolled into
http://www.noteshare.io[Noteshare.io].  Then the *Show Doc*
item in the *View* menu will compile the current notebook
with an index if the attribute `:make_index:` is set.
